//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Cliente()
        {
            this.Tbl_Reserva = new HashSet<Tbl_Reserva>();
        }
    
        public int IdCliente { get; set; }
        public System.DateTime Fecha_Registro { get; set; }
        public Nullable<int> Cant_Reservas { get; set; }
        public int IdPersona { get; set; }
        public int Estado { get; set; }
    
        public virtual Tbl_Persona Tbl_Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Reserva> Tbl_Reserva { get; set; }
    }
}
