//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Vehiculo()
        {
            this.Tbl_Reserva = new HashSet<Tbl_Reserva>();
        }
    
        public int IdVehiculo { get; set; }
        public string Placa { get; set; }
        public string Modelo { get; set; }
        public string Marca { get; set; }
        public string Kilometraje { get; set; }
        public string Color { get; set; }
        public string Tipo_Vehiculo { get; set; }
        public string Tipo_Combustible { get; set; }
        public Nullable<int> IdImagen { get; set; }
        public int Estado { get; set; }
    
        public virtual Tbl_Imagen Tbl_Imagen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Reserva> Tbl_Reserva { get; set; }
    }
}
