//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Empleado()
        {
            this.Tbl_Reserva = new HashSet<Tbl_Reserva>();
        }
    
        public int IdEmpleado { get; set; }
        public string Cargo { get; set; }
        public string Jefe_Inmediato { get; set; }
        public string Departamento { get; set; }
        public int IdUsuario { get; set; }
        public int Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Reserva> Tbl_Reserva { get; set; }
        public virtual Tbl_Usuario Tbl_Usuario { get; set; }
    }
}
