//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Reserva
    {
        public int IdReserva { get; set; }
        public string Descripcion { get; set; }
        public string TipoPago { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public System.DateTime FechaDevolucion { get; set; }
        public string Ciudad { get; set; }
        public decimal Monto { get; set; }
        public int IdCliente { get; set; }
        public int IdEmpleado { get; set; }
        public int IdVehiculo { get; set; }
    
        public virtual Tbl_Cliente Tbl_Cliente { get; set; }
        public virtual Tbl_Empleado Tbl_Empleado { get; set; }
        public virtual Tbl_Vehiculo Tbl_Vehiculo { get; set; }
    }
}
